# @TODO: Prefer Json - Gatsby depends on this unfortunately.
siteTitle="Charles Davis"
siteUrl="http://oliverbenns.com"
description="Oliver Benns is a freelance web developer working with individuals and agencies across the world."
